### ISSUE TITLE
Question about shapefile

### ISSUE THREAD

**Issue by kontrybutor** [szymon-datalions/projections-clouds-and-Gdansk-Bay#1]
Hi! 

Could you explain how have you created the shapefiles? Which program have you used? Is it free? I would like to go through step by step but with different ROI. 

Regards,
Rafał

**Comment by szymon-datalions** [comment]
PL: Nie wiem, czy już sobie poradziłeś z zagadnieniem czy nie, ale tworzenie plików wektorowych jest przedstawione na przykład tutaj: https://github.com/mtop/speciesgeocoder/wiki/Tutorial-for-creating-polygons-in-QGIS

ENG: Shapefiles may be created in QGIS: https://github.com/mtop/speciesgeocoder/wiki/Tutorial-for-creating-polygons-in-QGIS
